### ISSUE TITLE
[GKE] Add support for C4 and hyperdisk node pool 

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-8-helm-profiles#100]
```sh
gcloud beta container --project "camunda-researchanddevelopment" node-pools create "c4-standard-4" --cluster "falko-benchmark" --zone "europe-west1-b" --node-version "1.31.6-gke.1020000" --machine-type "c4-standard-4" --image-type "COS_CONTAINERD" --disk-type "hyperdisk-balanced" --disk-size "100" --metadata disable-legacy-endpoints=true --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --spot --num-nodes "0" --enable-autoscaling --total-min-nodes "0" --total-max-nodes "256" --location-policy "ANY" --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 --shielded-integrity-monitoring --shielded-secure-boot
```

**Comment by falko** [comment]
XFS seems to be good for hyperdisk:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-xfs
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced # Or hyperdisk-extreme, hyperdisk-throughput, hyperdisk-ml
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
