### ISSUE TITLE
Expected Storage Classes (documentation and minimising developer profile dependencies)

### ISSUE THREAD

**Issue by allanbarklie** [camunda-community-hub/camunda-8-helm-profiles#3]
I think this is a great initiative.
I'm initially interested in the developer profile.

I'm using Docker Desktop, the Kubernetes cluster by default only has the Storage Class 'hostpath'
I note that the developer profile relies on the existence of both   'hostpath' and 'standard'

At least one other storage class is introduced in the other profiles 'ssd'
It would be good to document these and consider if the developer profile should/could only need 'hostpath' by default.

**Comment by salaboy** [comment]
@allanbarklie that is definitely a good suggestion. Would you mind sending a PR for supporting setting 'hostpath' in our current charts? So we standardize that for local development.

**Comment by allanbarklie** [comment]
@salaboy I'm new to charts so just finding my feet.

From some more experimenting and reading my updated understanding is that a k8s cluster can have a default storage provider.  If any persistentvolumeclaim (including a template) leaves storage class blank (not an empty string, actually blank) then the default storage provider will be used.

For docker desktop that is a storage provider called _hostpath_ that uses the provisioner _docker.io/hostpath_
For GKE I believe the default storage provider is called _standard_

In the current version when I run it on docker desktop the zeebe broke ends up with a volume backed by _hostpath_ it gets that by leaving the storage class blank, as the current dev profile Helm chart does not set the Zeebe chart configuration field _pvcStorageClassName_ 

I would guess that when this is run on GKE _standard_ is used.

For elastic search the dev profile is currently explicitly setting _standard_, if instead storage class is left blank then on my system with docker desktop it successfully uses _hostpath_

I would guess that on GKE this will continue to use _standard_.

In my test I changed (in zeebe-dev-profile.yaml)
```
# Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 100M
```
to
```
# Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName:
      resources:
        requests:
          storage: 100M
```
If this sounds sensible I can commit the tweak and submit for the PR?
